env:
  global:
    secure: AH6JUSKRpfmfU/K0VqTBtwEZSNCUcP+JEYIWSNQ/HtbBXAPKfEp91ywOlRb6KQUv0anFtZH2UFL7C0CFY81sALfMEWKQXwi7SH4RjgO4mAfT6tmWb+CgeS98M2sY8oEnfX/Riv3cxvz1Yrq1vijZMY1GV3/TuBHKEMYecjMS1Ss=
language: java
jdk:
  - openjdk6
branches:
  only:
    - master
script: mvn -f com.codeaffine.archive.releng/pom.xml clean verify
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
after_success: 
  - chmod a+x .travis-deploy.sh
  - ./.travis-deploy.sh
after_failure:
  - cat com.codeaffine.archive.contenttype.test/target/surefire-reports/*.txt
  - cat com.codeaffine.archive.ui.test/target/surefire-reports/*.txt
  - cat com.codeaffine.archive.ui.itest/target/surefire-reports/*.txt
