env:
  global:
    secure: KDpz0qYqt5yI6mMW+ZXk5hwgz1SyY9yp/zVXQBx1uhvGTiyDwUJpv7bw1T5QeqtuNLAuFmz/6uPThCZucdU77VOQ9wuUaXrvD13KHA+v4LrJZ2pwnkZ6FZE4az0v+IHk6Y4mghyajuXUn2SgTXHHnAcahTd1Qesnn9UVu56xtBM=

dist: trusty

language: java

jdk:
  - openjdk8

branches:
  only:
  - master

install: true

before_install:
  - sudo apt-get update
  - sudo apt-get install gnome-themes-standard
  - sudo apt-get install metacity
  - sudo apt-get install libwebkit-dev

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - metacity --sm-disable --replace &
  - sleep 3

script:
  - jdk_switcher use openjdk8
  - mvn -f com.codeaffine.archive.releng/pom.xml -Dbrowser=webkit clean verify

after_success:
  - chmod a+x .travis-deploy.sh
  - ./.travis-deploy.sh

after_failure:
  - cat com.codeaffine.archive.contenttype.test/target/surefire-reports/*.txt
  - cat com.codeaffine.archive.ui.test/target/surefire-reports/*.txt
  - cat com.codeaffine.archive.ui.itest/target/surefire-reports/*.txt
